spring:
  application:
    name: springboot_union
  datasource:
    #url切换数据库之后如果对应数据库名称和路径有变动，需要修改url
    url: jdbc:mysql://120.26.103.95:3306/shangyu-pay?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wangjian2024@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10

  mvc:
    static-path-pattern: /**


mybatis:
  mapper-locations:  classpath:mapper/**/*.xml    #mapper文件位置
  type-aliases-package: com.example.wangjian.syslog1.entity    #实体类所在包（别名）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


alipay:
  appId: 9021000139647982
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCSXRHi5xnNW4fis/aFi1z5jf0nbUElwf/L4ZuYI16WBYTaHS34Ipjqzfshc8JGTuhVyW276En3eWOT73wRyRQmRw308cJr7oxioXYZnRYftn+cmp3B06/IIUlgPUH/okBy++5r0bDtlTcGashhL106dtNw9nAJvGGjuJeAD20N9wrzG7yK1Cd3BkwdsI47QGR99OSeH2eDsMeNI2o7pJbWVG/3m1LdtQpD6hFUvPzqMB7+AU5oLmOZC+Tu2eqlgxfsi+O9Ihgyah9kqgGEy+xqTwuk/RFB0y/bxUqsToD8twuNEfriDUEpYnMTtFD4WvKRCaODj7bb5Z2nmq0H8OyXAgMBAAECggEAP4fUfrgvc/saBaZ2CEuQ5OXkD9wVni0SOk5IeoZHxTjKDN8DmCR0Wd9k9YVIu7n+kVYooprWmGwBdDJMmW+9pkvLXBogeTcHirxpBf8wnj1aMQDQH1UihO0l63dLkYm9Dewa9oQDl2zggJGTPtQPVJRFfVALG77AZw91+2k2vgtokxAb00PwhVxdjxbP1T3OTxc5lsdraEXo0pt1HhEK5T7S2cHAFSwBJpbOeDN5YW5XRUvy3VvPXTStU2X6jf+Y0Qp5jQbmWVJ1dCLfkVVESK5R9Wl8SrvEyME8RgTWNJdogE6hoHuQcyUvFNxEE9G1obc9NDYQvDQsyoZ9HQUqeQKBgQDBomD5iKoyzsTGF81D1wPb5GbsOq2eRv8cfM48gAr4ARn5j33nJeiaxpk9Af3KJ8HoT24eIaXqNuP8B6bFaORVUS12I09y7LznpG03Uk/mwhHBCgpHwXxUavgorVZ0kGe003VJ22I7T+VlQ1mHkJvm7x8hNp6T4TPndaRQjW7ulQKBgQDBgRphER9mzN/rRNDcZyfLZItmPdY3I1KLwD8UQFrOce8OtCux50JwYlPaQzuWwBfeeaF4BfeCOHG7/xlRdYL9hyLUhSXLdCjAby3F2UbnP9fmmYN19blkyBWTdui/dUkcSW+bLMvA5n7g9iXqw7X/SCHdHcikCMUNDtzsfO9fewKBgFcSS4UqHU6nh/iD73uYDlYtCNMlN7k6t7D5tkuiUExhQmrkSXtNoqEmuPWkFZl380whm6TVAKSndjF4x1dx6WssC8NZ8Xn+VpvbZnk//EoJ7q3dc+38ZYoYZ+rytzPHU7sOc2l4y11cegzlEjdRoalg0aC/zOM2m35zeiX203FZAoGAH5Y9gh7Ta2qCGtuO5IuKOW9eOgBaGYIQlXN6WInwyMZcaaALiezgMYw7d+OFtKQCwXRFYVxH/N/N4QxRS7TM/ymyC9L4Sm/Zvx/m7ub65gDL836XsQe9jbADpaDBeY9hsdZi+4eicwitKXfE1L/B07womvmjqPMth2Yntgrm4EUCgYB7UFNj0pykFz6L7ZaWDTPwkaV0NPAxeFNaYXCarsSAOwiJknksg9oUjmliECb4DOwQsOg2N+VRIooOn/hIHoG7VJIySD9SfC+hldqpinZfIJyjV0/epICxaxqlHwJ/5vsoHvMZh/KnEuwtQ1PW86nVjhlduUtRMO4Rmpj/c0G81A==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhJxuL+3FpGcFURgww0zg3+9S/qnMg9tC7bCqM2zlWByd4/Hbov8MGm2yfaBoEFzYxSVzj+n3vCBXnuWIStis5OwrkX2XQxJ6aRSmAdIZs6Ry8OheSsu1kv7b5VgMzhV3tuXORL7XdF/GMNo2wfANSQ46wIj41+ojTgk8XYjBppcmjmhtfMteypanLg9dniEie5o/MHjING4chzkHzmVBEiTWdhiVD9pSZOZdpant80PeMWdbTvulLm1J68Tp/VT/wC6oTexo7xjipErs+vQn907F9LSGubt+8P6BA9/ieiDKKe1xhJwhJtRUTZICAwDBQk6KBkZONkoZoZPGDM/3nQIDAQAB
  notifyUrl: http://www.yuhangzhifu.cn:8331/log/alipay/notify
  gateWay: https://openapi-sandbox.dl.alipaydev.com/gateway.do


wechat:
  pay:
    mchId: 1682702563
    privateKeyPath: C:\mywecat\1682702563_20240806_cert\apiclient_key.pem
    merchantSerialNumber: 595537B7F38528B1C5204F71A1CD30EC3A3447AF
    apiV3key: f30fe11545b3beb62b3e5fb9171cd0a5
    platformCertPath: C:\mywecat\palent\wechatpay_5BC5958BD5AEAF67149B3AAEDB741AA8D7B8F6D5.pem

    appId: wxf66bcdbe7d24ba16
    notifyUrl: https://39sm833vw457.vicp.fun/log/wxpay/notify


